# application.yml 
--- 
spring:
  application: 
    name: cities
cities:
  restaurants:
    affi: Le tagliatelle di Nonna Pina, Casa del Kebab
    matera: Le Pizze di Pizzo, Abbondanza Lucana, Archetto
    roma: Don Carlos
    napoli: RossoPomodoro, Da Michele
specialties: Margherita, Bomba pugliese, Shrek, Panino o piadina?
server: 
  port: 8081
