# application.yml 
--- 
spring:
  application: 
    name: cities
restaurants: Le tagliatelle di Nonna Pina, Casa del Kebab, Le Pizze di Pizzo, Abbondanza Lucana, Archetto, Don Carlos, RossoPomodoro, Da Michele
specialties: Margherita, Bomba pugliese, Shrek, Panino o piadina?
server: 
  port: 8081
