# application.yml 
---
spring:
  application: 
    name: cities
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://eureka:8010/eureka/
  instance: 
    leaseRenewalIntervalInSeconds: 5
    metadataMap: 
      instanceId: ${spring.application.name}:${random.value}
cities:
  restaurants:
    affi: 
        - Le Pizze di Pizzo
        - Le tagliatelle di Nonna Pina
        - Casa del Kebab
    matera:
        - Abbondanza Lucana
        - Archetto
    roma: 
        - Don Carlos
    napoli: 
        - RossoPomodoro
        - Da Michele
  specialties: 
        - Margherita
        - Marinara
        - Salsiccia e Friarielli
        - Panino farcito
        - Spaghetti alle vongole
        - Risotto allo zenzero
        - Quattro Stagioni
        - Lasagna al forno
        - Spigola al forno
        - Tagliata di bovino
server: 
  port: ${PORT:${SERVER_PORT:0}}