# application.yml 
--- 
spring: 
  profiles: cities
  application: 
    name: cities
restaurants:
  affi:
    - Le Pizze di Pizzo
  matera:
    - Abbondanza Lucana
    - Le tagliatelle di Nonna Pina
    - Casa del Kebab
specialties:
  - Margherita
  - Bomba pugliese
  - Shrek
  - Panino o piadina?
server: 
  port: 8081
