version: '3'

services:
  eureka:
    image: swarm.inf.uniroma3.it:5000/eureka-9009
    deploy:
      placement:
        constraints: [node.role == manager]
    
  cities:
    image: swarm.inf.uniroma3.it:5000/cities-9009
    depends_on: 
      - "eureka"
    deploy:
      mode: replicated
      replicas: 1

  ratings:
    image: swarm.inf.uniroma3.it:5000/ratings-9009
    depends_on: 
      - "eureka"
    deploy:
      mode: replicated
      replicas: 1

  restaurants:
    image: swarm.inf.uniroma3.it:5000/restaurants-9009
    depends_on: 
      - "eureka"
    deploy:
      mode: replicated
      replicas: 2

  zuul:
    image: swarm.inf.uniroma3.it:5000/zuul-9009
    depends_on: 
      - "eureka"
    ports:
      - "9009:8080"
