# application.yml 
--- 
spring: 
  profiles: restaurants
  application: 
    name: restaurants
city.uri: http://localhost:8081 
rating.uri: http://localhost:8082 
server:
  port: 8080

--- 
spring: 
  profiles: cities
  application: 
    name: cities
restaurants:
  affi:
    - Le Pizze di Pizzo
  matera:
    - Abbondanza Lucana
    - Le tagliatelle di Nonna Pina
    - Casa del Kebab
specialties:
  - Margherita
  - Bomba pugliese
  - Shrek
  - Panino o piadina?
server: 
  port: 8081
  
--- 
spring: 
  profiles: ratings
  application: 
    name: ratings
server: 
  port: 8082
