# application.yml 
--- 
spring:
  application: 
    name: restaurants
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://eureka:8010/eureka/
  instance: 
    leaseRenewalIntervalInSeconds: 5
    metadataMap: 
      instanceId: ${spring.application.name}:${random.value}
server: 
  port: ${PORT:${SERVER_PORT:0}}