# application.yml 
--- 
spring:
  application: 
    name: restaurants
city.uri: http://localhost:8081/S1/{city}/{restaurant}
rating.uri: http://localhost:8082/S2/{city}/{restaurant}
server:
  port: 8080
