VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "ubuntu/trusty64"
    config.vm.synced_folder "../../", "/home/vagrant/projects", :mount_options => ["dmode=777", "fmode=777"]
    config.vm.synced_folder "../shared/", "/home/vagrant/shared", :mount_options => ["dmode=777", "fmode=777"]

    config.vm.define "dev" do |node|
        node.vm.hostname = "dev"    
	
	#Usiamo come IP della VM uno "abbastanza" poco usato
        node.vm.network "private_network", ip: "127.0.0.2", virtualbox__intnet: true

        node.vm.provider "virtualbox" do |v| 
	    v.memory = 4096 
            v.cpus = 2
        end 

        node.vm.network "forwarded_port", guest: 22, host: 2222, id: 'ssh', auto_correct: true 
        node.ssh.forward_agent = true
 
        # Pubblichiamo le porte utili ai servizi, forwardandole su 8088-8089-8090
        node.vm.network "forwarded_port", guest: 8080, host: 8088, id: 'http', auto_correct: true
	node.vm.network "forwarded_port", guest: 8081, host: 8089, id: 'http1', auto_correct: true
	node.vm.network "forwarded_port", guest: 8082, host: 8090, id: 'http2', auto_correct: true

        node.vm.provision :shell, :inline => 'apt-get update'
        node.vm.provision :shell, path: "../shared/scripts/setup-java.sh"
        node.vm.provision :shell, path: "../shared/scripts/setup-gradle.sh"
        node.vm.provision :shell, path: "../shared/scripts/setup-maven.sh"
  
        node.vm.provision :shell, 
            inline: "echo  'configurazione nodo developer completata'"

    end

end
